<?php

namespace App\Core\Download;

class SymbiotaNative {
    use DeriveCombineOccurrenceRecordID;
    use DeriveOccurrenceReference;
    use RowMap;

    public static $metaType = 'core';

    //TODO (Logan) double check if this is correct
    public static $metaRowType = 'http://rs.tdwg.org/dwc/terms/Occurrence';

    public static $casts = [
        'occid' => 'id',
        'tidInterpreted' => 'taxonID',
        'taxonRank' => 'verbatimTaxonRank',
        'sourcePrimaryKey-dbpk' => 'dbpk',
        'dateLastModified' => 'modified',
    ];

    public static $ignores = [];

    public static $derived = [
        'references' => 'derive_references',
        'recordID' => 'derive_combine_occurrence_record_id',
        'occurrenceID' => 'derive_combine_occurrence_record_id',
    ];

    public static $fields = [
        'id' => null,
        'institutionCode' => null,
        'collectionCode' => null,
        'ownerInstitutionCode' => null,
        'basisOfRecord' => null,
        'occurrenceID' => null,
        'catalogNumber' => null,
        'otherCatalogNumbers' => null,
        'higherClassification' => null,
        'kingdom' => null,
        'phylum' => null,
        'class' => null,
        'order' => null,
        'subgenus' => null,
        'family' => null,
        'scientificName' => null,
        'taxonID' => null,
        'scientificNameAuthorship' => null,
        'genus' => null,
        'specificEpithet' => null,
        'verbatimTaxonRank' => null,
        'infraspecificEpithet' => null,
        'cultivarEpithet' => null,
        'tradeName' => null,
        'taxonRank' => null,
        'identifiedBy' => null,
        'dateIdentified' => null,
        'identificationReferences' => null,
        'identificationRemarks' => null,
        'taxonRemarks' => null,
        'identificationQualifier' => null,
        'typeStatus' => null,
        'recordedBy' => null,
        'associatedCollectors' => null,
        'recordNumber' => null,
        'eventDate' => null,
        'eventDate2' => null,
        'year' => null,
        'month' => null,
        'day' => null,
        'startDayOfYear' => null,
        'endDayOfYear' => null,
        'verbatimEventDate' => null,
        'occurrenceRemarks' => null,
        'habitat' => null,
        'substrate' => null,
        'verbatimAttributes' => null,
        'behavior' => null,
        'vitality' => null,
        'fieldNumber' => null,
        'eventID' => null,
        'informationWithheld' => null,
        'dataGeneralizations' => null,
        'dynamicProperties' => null,
        'associatedOccurrences' => null,
        'associatedSequences' => null,
        'associatedTaxa' => null,
        'reproductiveCondition' => null,
        'establishmentMeans' => null,
        'cultivationStatus' => null,
        'lifeStage' => null,
        'sex' => null,
        'individualCount' => null,
        'samplingProtocol' => null,
        'preparations' => null,
        'locationID' => null,
        'continent' => null,
        'waterBody' => null,
        'islandGroup' => null,
        'island' => null,
        'country' => null,
        'countryCode' => null,
        'stateProvince' => null,
        'county' => null,
        'municipality' => null,
        'locality' => null,
        'locationRemarks' => null,
        'localitySecurity' => null,
        'localitySecurityReason' => null,
        'decimalLatitude' => null,
        'decimalLongitude' => null,
        'geodeticDatum' => null,
        'coordinateUncertaintyInMeters' => null,
        'verbatimCoordinates' => null,
        'georeferencedBy' => null,
        'georeferenceProtocol' => null,
        'georeferenceSources' => null,
        'georeferenceVerificationStatus' => null,
        'georeferenceRemarks' => null,
        'minimumElevationInMeters' => null,
        'maximumElevationInMeters' => null,
        'minimumDepthInMeters' => null,
        'maximumDepthInMeters' => null,
        'verbatimDepth' => null,
        'verbatimElevation' => null,
        'disposition' => null,
        'language' => null,
        'recordEnteredBy' => null,
        'modified' => null,
        'sourcePrimaryKey-dbpk' => null,
        'collid' => null,
        'recordID' => null,
        'references' => null,
    ];
}
