@php
$items = [
    ['title'=> 'Associated Collectors', 'value' => 'associatedCollectors', 'disabled' => false ],
    ['title'=> 'Associated Occurrences', 'value' => 'associatedOccurrences', 'disabled' => false ],
    ['title'=> 'Associated Taxa', 'value' => 'associatedTaxa', 'disabled' => false ],
    ['title'=> 'Attributes', 'value' => 'attributes', 'disabled' => false ],
    ['title'=> 'Author', 'value' => 'scientificNameAuthorship', 'disabled' => false ],
    ['title'=> 'Basis Of Record', 'value' => 'basisOfRecord', 'disabled' => false ],
    ['title'=> 'Behavior', 'value' => 'behavior', 'disabled' => false ],
    ['title'=> 'Catalog Number', 'value' => 'catalogNumber', 'disabled' => false ],
    ['title'=> 'Collection Code (override)', 'value' => 'collectionCode', 'disabled' => false ],
    ['title'=> 'Collector Number', 'value' => 'recordNumber', 'disabled' => false ],
    ['title'=> 'Collector/Observer', 'value' => 'recordedBy', 'disabled' => false ],
    ['title'=> 'Coordinate Uncertainty (m)', 'value' => 'coordinateUncertaintyInMeters', 'disabled' => false ],
    ['title'=> 'Country', 'value' => 'country', 'disabled' => false ],
    ['title'=> 'County', 'value' => 'county', 'disabled' => false ],
    ['title'=> 'Cultivation Status', 'value' => 'cultivationStatus', 'disabled' => false ],
    ['title'=> 'Data Generalizations', 'value' => 'dataGeneralizations', 'disabled' => false ],
    ['title'=> 'Date', 'value' => 'eventDate', 'disabled' => false ],
    ['title'=> 'Date Entered', 'value' => 'dateEntered', 'disabled' => false ],
    ['title'=> 'Date Last Modified', 'value' => 'dateLastModified', 'disabled' => false ],
    ['title'=> 'dbpk', 'value' => 'dbpk', 'disabled' => false ],
    ['title'=> 'Decimal Latitude', 'value' => 'decimalLatitude', 'disabled' => false ],
    ['title'=> 'Decimal Longitude', 'value' => 'decimalLongitude', 'disabled' => false ],
    ['title'=> 'Depth Maximum (m)', 'value' => 'maximumDepthInMeters', 'disabled' => false ],
    ['title'=> 'Depth Minimum (m)', 'value' => 'minimumDepthInMeters', 'disabled' => false ],
    ['title'=> 'Description', 'value' => 'verbatimAttributes', 'disabled' => false ],
    ['title'=> 'Disposition', 'value' => 'disposition', 'disabled' => false ],
    ['title'=> 'Dynamic Properties', 'value' => 'dynamicProperties', 'disabled' => false ],
    ['title'=> 'Elevation Maximum (m)', 'value' => 'maximumElevationInMeters', 'disabled' => false ],
    ['title'=> 'Elevation Minimum (m)', 'value' => 'minimumElevationInMeters', 'disabled' => false ],
    ['title'=> 'Establishment Means', 'value' => 'establishmentMeans', 'disabled' => false ],
    ['title'=> 'Family', 'value' => 'family', 'disabled' => false ],
    ['title'=> 'Field Notes', 'value' => 'fieldNotes', 'disabled' => false ],
    ['title'=> 'Field Number', 'value' => 'fieldnumber', 'disabled' => false ],
    ['title'=> 'Geodetic Datum', 'value' => 'geodeticDatum', 'disabled' => false ],
    ['title'=> 'Georeference Protocol', 'value' => 'georeferenceProtocol', 'disabled' => false ],
    ['title'=> 'Georeference Remarks', 'value' => 'georeferenceRemarks', 'disabled' => false ],
    ['title'=> 'Georeference Sources', 'value' => 'georeferenceSources', 'disabled' => false ],
    ['title'=> 'Georeference Verification Status', 'value' => 'georeferenceVerificationStatus', 'disabled' => false ],
    ['title'=> 'Georeferenced By', 'value' => 'georeferencedBy', 'disabled' => false ],
    ['title'=> 'Habitat', 'value' => 'habitat', 'disabled' => false ],
    ['title'=> 'Identification Qualifier', 'value' => 'identificationQualifier', 'disabled' => false ],
    ['title'=> 'Identification References', 'value' => 'identificationReferences', 'disabled' => false ],
    ['title'=> 'Identification Remarks', 'value' => 'identificationRemarks', 'disabled' => false ],
    ['title'=> 'Identified By', 'value' => 'identifiedBy', 'disabled' => false ],
    ['title'=> 'Individual Count', 'value' => 'individualCount', 'disabled' => false ],
    ['title'=> 'Information Withheld', 'value' => 'informationWithheld', 'disabled' => false ],
    ['title'=> 'Institution Code (override)', 'value' => 'institutionCode', 'disabled' => false ],
    ['title'=> 'Label Project', 'value' => 'labelProject', 'disabled' => false ],
    ['title'=> 'Language', 'value' => 'language', 'disabled' => false ],
    ['title'=> 'Life Stage', 'value' => 'lifeStage', 'disabled' => false ],
    ['title'=> 'Location ID', 'value' => 'locationid', 'disabled' => false ],
    ['title'=> 'Locality', 'value' => 'locality', 'disabled' => false ],
    ['title'=> 'Locality Security', 'value' => 'localitySecurity', 'disabled' => false ],
    ['title'=> 'Locality Security Reason', 'value' => 'localitySecurityReason', 'disabled' => false ],
    ['title'=> 'Location Remarks', 'value' => 'locationRemarks', 'disabled' => false ],
    ['title'=> 'Modified By', 'value' => 'username', 'disabled' => false ],
    ['title'=> 'Municipality', 'value' => 'municipality', 'disabled' => false ],
    ['title'=> 'Notes (Occurrence Remarks)', 'value' => 'occurrenceRemarks', 'disabled' => false ],
    ['title'=> 'OCR Fragment', 'value' => 'ocrFragment', 'disabled' => false ],
    ['title'=> 'Other Catalog Numbers', 'value' => 'otherCatalogNumbers', 'disabled' => false ],
    ['title'=> 'Owner Code', 'value' => 'ownerInstitutionCode', 'disabled' => false ],
    ['title'=> 'Preparations', 'value' => 'preparations', 'disabled' => false ],
    ['title'=> 'Reproductive Condition', 'value' => 'reproductiveCondition', 'disabled' => false ],
    ['title'=> 'Sampling Effort', 'value' => 'samplingEffort', 'disabled' => false ],
    ['title'=> 'Sampling Protocol', 'value' => 'samplingProtocol', 'disabled' => false ],
    ['title'=> 'Scientific Name', 'value' => 'sciname', 'disabled' => false ],
    ['title'=> 'Sex', 'value' => 'sex', 'disabled' => false ],
    ['title'=> 'State/Province', 'value' => 'stateProvince', 'disabled' => false ],
    ['title'=> 'Substrate', 'value' => 'substrate', 'disabled' => false ],
    ['title'=> 'Taxon Remarks', 'value' => 'taxonRemarks', 'disabled' => false ],
    ['title'=> 'Type Status', 'value' => 'typeStatus', 'disabled' => false ],
    ['title'=> 'Verbatim Coordinates', 'value' => 'verbatimCoordinates', 'disabled' => false ],
    ['title'=> 'Verbatim Date', 'value' => 'verbatimEventDate', 'disabled' => false ],
    ['title'=> 'Verbatim Depth', 'value' => 'verbatimDepth', 'disabled' => false ],
    ['title'=> 'Verbatim Elevation', 'value' => 'verbatimElevation', 'disabled' => false ],
];
@endphp
<x-select :items="$items" {{ $attributes }} />
