<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class() extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void {
        DB::table('taxauthority')->insertOrIgnore([
            'taxauthid'        => 1,
            'isprimary'        => 1,
            'name'             => 'Central Thesaurus',
            'description'      => null,
            'editors'          => null,
            'contact'          => null,
            'email'            => null,
            'url'              => null,
            'notes'            => null,
            'isactive'         => 1,
            'initialtimestamp' => '2023-03-26 18:14:32',
        ]);

        DB::table('taxonunits')->insertOrIgnore([
            // Organism kingdom
            ['taxonunitid' => 24,  'kingdomName' => 'Organism', 'rankid' => 1,   'rankname' => 'Organism',    'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 25,  'kingdomName' => 'Organism', 'rankid' => 10,  'rankname' => 'Kingdom',     'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 26,  'kingdomName' => 'Organism', 'rankid' => 20,  'rankname' => 'Subkingdom',  'suffix' => null, 'dirparentrankid' => 10,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 27,  'kingdomName' => 'Organism', 'rankid' => 30,  'rankname' => 'Division',    'suffix' => null, 'dirparentrankid' => 20,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 28,  'kingdomName' => 'Organism', 'rankid' => 40,  'rankname' => 'Subdivision', 'suffix' => null, 'dirparentrankid' => 30,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 29,  'kingdomName' => 'Organism', 'rankid' => 50,  'rankname' => 'Superclass',  'suffix' => null, 'dirparentrankid' => 40,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 30,  'kingdomName' => 'Organism', 'rankid' => 60,  'rankname' => 'Class',       'suffix' => null, 'dirparentrankid' => 50,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 31,  'kingdomName' => 'Organism', 'rankid' => 70,  'rankname' => 'Subclass',    'suffix' => null, 'dirparentrankid' => 60,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 32,  'kingdomName' => 'Organism', 'rankid' => 100, 'rankname' => 'Order',       'suffix' => null, 'dirparentrankid' => 70,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 33,  'kingdomName' => 'Organism', 'rankid' => 110, 'rankname' => 'Suborder',    'suffix' => null, 'dirparentrankid' => 100, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 34,  'kingdomName' => 'Organism', 'rankid' => 140, 'rankname' => 'Family',      'suffix' => null, 'dirparentrankid' => 110, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 35,  'kingdomName' => 'Organism', 'rankid' => 150, 'rankname' => 'Subfamily',   'suffix' => null, 'dirparentrankid' => 140, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 36,  'kingdomName' => 'Organism', 'rankid' => 160, 'rankname' => 'Tribe',       'suffix' => null, 'dirparentrankid' => 150, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 37,  'kingdomName' => 'Organism', 'rankid' => 170, 'rankname' => 'Subtribe',    'suffix' => null, 'dirparentrankid' => 160, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 38,  'kingdomName' => 'Organism', 'rankid' => 180, 'rankname' => 'Genus',       'suffix' => null, 'dirparentrankid' => 170, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 39,  'kingdomName' => 'Organism', 'rankid' => 190, 'rankname' => 'Subgenus',    'suffix' => null, 'dirparentrankid' => 180, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 40,  'kingdomName' => 'Organism', 'rankid' => 200, 'rankname' => 'Section',     'suffix' => null, 'dirparentrankid' => 190, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 41,  'kingdomName' => 'Organism', 'rankid' => 210, 'rankname' => 'Subsection',  'suffix' => null, 'dirparentrankid' => 200, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 42,  'kingdomName' => 'Organism', 'rankid' => 220, 'rankname' => 'Species',     'suffix' => null, 'dirparentrankid' => 210, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 43,  'kingdomName' => 'Organism', 'rankid' => 230, 'rankname' => 'Subspecies',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 44,  'kingdomName' => 'Organism', 'rankid' => 240, 'rankname' => 'Variety',     'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 45,  'kingdomName' => 'Organism', 'rankid' => 250, 'rankname' => 'Subvariety',  'suffix' => null, 'dirparentrankid' => 240, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 46,  'kingdomName' => 'Organism', 'rankid' => 260, 'rankname' => 'Form',        'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 47,  'kingdomName' => 'Organism', 'rankid' => 270, 'rankname' => 'Subform',     'suffix' => null, 'dirparentrankid' => 260, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 48,  'kingdomName' => 'Organism', 'rankid' => 300, 'rankname' => 'Cultivated',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 220, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            // Monera kingdom
            ['taxonunitid' => 49,  'kingdomName' => 'Monera',   'rankid' => 1,   'rankname' => 'Organism',    'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 50,  'kingdomName' => 'Monera',   'rankid' => 10,  'rankname' => 'Kingdom',     'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 51,  'kingdomName' => 'Monera',   'rankid' => 20,  'rankname' => 'Subkingdom',  'suffix' => null, 'dirparentrankid' => 10,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 52,  'kingdomName' => 'Monera',   'rankid' => 30,  'rankname' => 'Phylum',      'suffix' => null, 'dirparentrankid' => 20,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 53,  'kingdomName' => 'Monera',   'rankid' => 40,  'rankname' => 'Subphylum',   'suffix' => null, 'dirparentrankid' => 30,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 54,  'kingdomName' => 'Monera',   'rankid' => 60,  'rankname' => 'Class',       'suffix' => null, 'dirparentrankid' => 50,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 55,  'kingdomName' => 'Monera',   'rankid' => 70,  'rankname' => 'Subclass',    'suffix' => null, 'dirparentrankid' => 60,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 56,  'kingdomName' => 'Monera',   'rankid' => 100, 'rankname' => 'Order',       'suffix' => null, 'dirparentrankid' => 70,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 57,  'kingdomName' => 'Monera',   'rankid' => 110, 'rankname' => 'Suborder',    'suffix' => null, 'dirparentrankid' => 100, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 58,  'kingdomName' => 'Monera',   'rankid' => 140, 'rankname' => 'Family',      'suffix' => null, 'dirparentrankid' => 110, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 59,  'kingdomName' => 'Monera',   'rankid' => 150, 'rankname' => 'Subfamily',   'suffix' => null, 'dirparentrankid' => 140, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 60,  'kingdomName' => 'Monera',   'rankid' => 160, 'rankname' => 'Tribe',       'suffix' => null, 'dirparentrankid' => 150, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 61,  'kingdomName' => 'Monera',   'rankid' => 170, 'rankname' => 'Subtribe',    'suffix' => null, 'dirparentrankid' => 160, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 62,  'kingdomName' => 'Monera',   'rankid' => 180, 'rankname' => 'Genus',       'suffix' => null, 'dirparentrankid' => 170, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 63,  'kingdomName' => 'Monera',   'rankid' => 190, 'rankname' => 'Subgenus',    'suffix' => null, 'dirparentrankid' => 180, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 64,  'kingdomName' => 'Monera',   'rankid' => 220, 'rankname' => 'Species',     'suffix' => null, 'dirparentrankid' => 210, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 65,  'kingdomName' => 'Monera',   'rankid' => 230, 'rankname' => 'Subspecies',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 66,  'kingdomName' => 'Monera',   'rankid' => 240, 'rankname' => 'Morph',       'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            // Protista kingdom
            ['taxonunitid' => 67,  'kingdomName' => 'Protista', 'rankid' => 1,   'rankname' => 'Organism',    'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 68,  'kingdomName' => 'Protista', 'rankid' => 10,  'rankname' => 'Kingdom',     'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 69,  'kingdomName' => 'Protista', 'rankid' => 20,  'rankname' => 'Subkingdom',  'suffix' => null, 'dirparentrankid' => 10,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 70,  'kingdomName' => 'Protista', 'rankid' => 30,  'rankname' => 'Phylum',      'suffix' => null, 'dirparentrankid' => 20,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 71,  'kingdomName' => 'Protista', 'rankid' => 40,  'rankname' => 'Subphylum',   'suffix' => null, 'dirparentrankid' => 30,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 72,  'kingdomName' => 'Protista', 'rankid' => 60,  'rankname' => 'Class',       'suffix' => null, 'dirparentrankid' => 50,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 73,  'kingdomName' => 'Protista', 'rankid' => 70,  'rankname' => 'Subclass',    'suffix' => null, 'dirparentrankid' => 60,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 74,  'kingdomName' => 'Protista', 'rankid' => 100, 'rankname' => 'Order',       'suffix' => null, 'dirparentrankid' => 70,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 75,  'kingdomName' => 'Protista', 'rankid' => 110, 'rankname' => 'Suborder',    'suffix' => null, 'dirparentrankid' => 100, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 76,  'kingdomName' => 'Protista', 'rankid' => 140, 'rankname' => 'Family',      'suffix' => null, 'dirparentrankid' => 110, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 77,  'kingdomName' => 'Protista', 'rankid' => 150, 'rankname' => 'Subfamily',   'suffix' => null, 'dirparentrankid' => 140, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 78,  'kingdomName' => 'Protista', 'rankid' => 160, 'rankname' => 'Tribe',       'suffix' => null, 'dirparentrankid' => 150, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 79,  'kingdomName' => 'Protista', 'rankid' => 170, 'rankname' => 'Subtribe',    'suffix' => null, 'dirparentrankid' => 160, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 80,  'kingdomName' => 'Protista', 'rankid' => 180, 'rankname' => 'Genus',       'suffix' => null, 'dirparentrankid' => 170, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 81,  'kingdomName' => 'Protista', 'rankid' => 190, 'rankname' => 'Subgenus',    'suffix' => null, 'dirparentrankid' => 180, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 82,  'kingdomName' => 'Protista', 'rankid' => 220, 'rankname' => 'Species',     'suffix' => null, 'dirparentrankid' => 210, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 83,  'kingdomName' => 'Protista', 'rankid' => 230, 'rankname' => 'Subspecies',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 84,  'kingdomName' => 'Protista', 'rankid' => 240, 'rankname' => 'Morph',       'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            // Plantae kingdom
            ['taxonunitid' => 85,  'kingdomName' => 'Plantae',  'rankid' => 1,   'rankname' => 'Organism',    'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 86,  'kingdomName' => 'Plantae',  'rankid' => 10,  'rankname' => 'Kingdom',     'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 87,  'kingdomName' => 'Plantae',  'rankid' => 20,  'rankname' => 'Subkingdom',  'suffix' => null, 'dirparentrankid' => 10,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 88,  'kingdomName' => 'Plantae',  'rankid' => 30,  'rankname' => 'Division',    'suffix' => null, 'dirparentrankid' => 20,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 89,  'kingdomName' => 'Plantae',  'rankid' => 40,  'rankname' => 'Subdivision', 'suffix' => null, 'dirparentrankid' => 30,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 90,  'kingdomName' => 'Plantae',  'rankid' => 50,  'rankname' => 'Superclass',  'suffix' => null, 'dirparentrankid' => 40,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 91,  'kingdomName' => 'Plantae',  'rankid' => 60,  'rankname' => 'Class',       'suffix' => null, 'dirparentrankid' => 50,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 92,  'kingdomName' => 'Plantae',  'rankid' => 70,  'rankname' => 'Subclass',    'suffix' => null, 'dirparentrankid' => 60,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 93,  'kingdomName' => 'Plantae',  'rankid' => 100, 'rankname' => 'Order',       'suffix' => null, 'dirparentrankid' => 70,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 94,  'kingdomName' => 'Plantae',  'rankid' => 110, 'rankname' => 'Suborder',    'suffix' => null, 'dirparentrankid' => 100, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 95,  'kingdomName' => 'Plantae',  'rankid' => 140, 'rankname' => 'Family',      'suffix' => null, 'dirparentrankid' => 110, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 96,  'kingdomName' => 'Plantae',  'rankid' => 150, 'rankname' => 'Subfamily',   'suffix' => null, 'dirparentrankid' => 140, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 97,  'kingdomName' => 'Plantae',  'rankid' => 160, 'rankname' => 'Tribe',       'suffix' => null, 'dirparentrankid' => 150, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 98,  'kingdomName' => 'Plantae',  'rankid' => 170, 'rankname' => 'Subtribe',    'suffix' => null, 'dirparentrankid' => 160, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 99,  'kingdomName' => 'Plantae',  'rankid' => 180, 'rankname' => 'Genus',       'suffix' => null, 'dirparentrankid' => 170, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 100, 'kingdomName' => 'Plantae',  'rankid' => 190, 'rankname' => 'Subgenus',    'suffix' => null, 'dirparentrankid' => 180, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 101, 'kingdomName' => 'Plantae',  'rankid' => 200, 'rankname' => 'Section',     'suffix' => null, 'dirparentrankid' => 190, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 102, 'kingdomName' => 'Plantae',  'rankid' => 210, 'rankname' => 'Subsection',  'suffix' => null, 'dirparentrankid' => 200, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 103, 'kingdomName' => 'Plantae',  'rankid' => 220, 'rankname' => 'Species',     'suffix' => null, 'dirparentrankid' => 210, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 104, 'kingdomName' => 'Plantae',  'rankid' => 230, 'rankname' => 'Subspecies',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 105, 'kingdomName' => 'Plantae',  'rankid' => 240, 'rankname' => 'Variety',     'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 106, 'kingdomName' => 'Plantae',  'rankid' => 250, 'rankname' => 'Subvariety',  'suffix' => null, 'dirparentrankid' => 240, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 107, 'kingdomName' => 'Plantae',  'rankid' => 260, 'rankname' => 'Form',        'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 108, 'kingdomName' => 'Plantae',  'rankid' => 270, 'rankname' => 'Subform',     'suffix' => null, 'dirparentrankid' => 260, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 109, 'kingdomName' => 'Plantae',  'rankid' => 300, 'rankname' => 'Cultivated',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 220, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            // Fungi kingdom
            ['taxonunitid' => 110, 'kingdomName' => 'Fungi',    'rankid' => 1,   'rankname' => 'Organism',    'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 111, 'kingdomName' => 'Fungi',    'rankid' => 10,  'rankname' => 'Kingdom',     'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 112, 'kingdomName' => 'Fungi',    'rankid' => 20,  'rankname' => 'Subkingdom',  'suffix' => null, 'dirparentrankid' => 10,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 113, 'kingdomName' => 'Fungi',    'rankid' => 30,  'rankname' => 'Division',    'suffix' => null, 'dirparentrankid' => 20,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 114, 'kingdomName' => 'Fungi',    'rankid' => 40,  'rankname' => 'Subdivision', 'suffix' => null, 'dirparentrankid' => 30,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 115, 'kingdomName' => 'Fungi',    'rankid' => 50,  'rankname' => 'Superclass',  'suffix' => null, 'dirparentrankid' => 40,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 116, 'kingdomName' => 'Fungi',    'rankid' => 60,  'rankname' => 'Class',       'suffix' => null, 'dirparentrankid' => 50,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 117, 'kingdomName' => 'Fungi',    'rankid' => 70,  'rankname' => 'Subclass',    'suffix' => null, 'dirparentrankid' => 60,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 118, 'kingdomName' => 'Fungi',    'rankid' => 100, 'rankname' => 'Order',       'suffix' => null, 'dirparentrankid' => 70,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 119, 'kingdomName' => 'Fungi',    'rankid' => 110, 'rankname' => 'Suborder',    'suffix' => null, 'dirparentrankid' => 100, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 120, 'kingdomName' => 'Fungi',    'rankid' => 140, 'rankname' => 'Family',      'suffix' => null, 'dirparentrankid' => 110, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 121, 'kingdomName' => 'Fungi',    'rankid' => 150, 'rankname' => 'Subfamily',   'suffix' => null, 'dirparentrankid' => 140, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 122, 'kingdomName' => 'Fungi',    'rankid' => 160, 'rankname' => 'Tribe',       'suffix' => null, 'dirparentrankid' => 150, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 123, 'kingdomName' => 'Fungi',    'rankid' => 170, 'rankname' => 'Subtribe',    'suffix' => null, 'dirparentrankid' => 160, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 124, 'kingdomName' => 'Fungi',    'rankid' => 180, 'rankname' => 'Genus',       'suffix' => null, 'dirparentrankid' => 170, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 125, 'kingdomName' => 'Fungi',    'rankid' => 190, 'rankname' => 'Subgenus',    'suffix' => null, 'dirparentrankid' => 180, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 126, 'kingdomName' => 'Fungi',    'rankid' => 200, 'rankname' => 'Section',     'suffix' => null, 'dirparentrankid' => 190, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 127, 'kingdomName' => 'Fungi',    'rankid' => 210, 'rankname' => 'Subsection',  'suffix' => null, 'dirparentrankid' => 200, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 128, 'kingdomName' => 'Fungi',    'rankid' => 220, 'rankname' => 'Species',     'suffix' => null, 'dirparentrankid' => 210, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 129, 'kingdomName' => 'Fungi',    'rankid' => 230, 'rankname' => 'Subspecies',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 130, 'kingdomName' => 'Fungi',    'rankid' => 240, 'rankname' => 'Variety',     'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 131, 'kingdomName' => 'Fungi',    'rankid' => 250, 'rankname' => 'Subvariety',  'suffix' => null, 'dirparentrankid' => 240, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 132, 'kingdomName' => 'Fungi',    'rankid' => 260, 'rankname' => 'Form',        'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 133, 'kingdomName' => 'Fungi',    'rankid' => 270, 'rankname' => 'Subform',     'suffix' => null, 'dirparentrankid' => 260, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 134, 'kingdomName' => 'Fungi',    'rankid' => 300, 'rankname' => 'Cultivated',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 220, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            // Animalia kingdom
            ['taxonunitid' => 135, 'kingdomName' => 'Animalia', 'rankid' => 1,   'rankname' => 'Organism',    'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 136, 'kingdomName' => 'Animalia', 'rankid' => 10,  'rankname' => 'Kingdom',     'suffix' => null, 'dirparentrankid' => 1,   'reqparentrankid' => 1,   'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 137, 'kingdomName' => 'Animalia', 'rankid' => 20,  'rankname' => 'Subkingdom',  'suffix' => null, 'dirparentrankid' => 10,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 138, 'kingdomName' => 'Animalia', 'rankid' => 30,  'rankname' => 'Phylum',      'suffix' => null, 'dirparentrankid' => 20,  'reqparentrankid' => 10,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 139, 'kingdomName' => 'Animalia', 'rankid' => 40,  'rankname' => 'Subphylum',   'suffix' => null, 'dirparentrankid' => 30,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 140, 'kingdomName' => 'Animalia', 'rankid' => 60,  'rankname' => 'Class',       'suffix' => null, 'dirparentrankid' => 50,  'reqparentrankid' => 30,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 141, 'kingdomName' => 'Animalia', 'rankid' => 70,  'rankname' => 'Subclass',    'suffix' => null, 'dirparentrankid' => 60,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 142, 'kingdomName' => 'Animalia', 'rankid' => 100, 'rankname' => 'Order',       'suffix' => null, 'dirparentrankid' => 70,  'reqparentrankid' => 60,  'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 143, 'kingdomName' => 'Animalia', 'rankid' => 110, 'rankname' => 'Suborder',    'suffix' => null, 'dirparentrankid' => 100, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 144, 'kingdomName' => 'Animalia', 'rankid' => 140, 'rankname' => 'Family',      'suffix' => null, 'dirparentrankid' => 110, 'reqparentrankid' => 100, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 145, 'kingdomName' => 'Animalia', 'rankid' => 150, 'rankname' => 'Subfamily',   'suffix' => null, 'dirparentrankid' => 140, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 146, 'kingdomName' => 'Animalia', 'rankid' => 160, 'rankname' => 'Tribe',       'suffix' => null, 'dirparentrankid' => 150, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 147, 'kingdomName' => 'Animalia', 'rankid' => 170, 'rankname' => 'Subtribe',    'suffix' => null, 'dirparentrankid' => 160, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 148, 'kingdomName' => 'Animalia', 'rankid' => 180, 'rankname' => 'Genus',       'suffix' => null, 'dirparentrankid' => 170, 'reqparentrankid' => 140, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 149, 'kingdomName' => 'Animalia', 'rankid' => 190, 'rankname' => 'Subgenus',    'suffix' => null, 'dirparentrankid' => 180, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 150, 'kingdomName' => 'Animalia', 'rankid' => 220, 'rankname' => 'Species',     'suffix' => null, 'dirparentrankid' => 210, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 151, 'kingdomName' => 'Animalia', 'rankid' => 230, 'rankname' => 'Subspecies',  'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
            ['taxonunitid' => 152, 'kingdomName' => 'Animalia', 'rankid' => 240, 'rankname' => 'Morph',       'suffix' => null, 'dirparentrankid' => 220, 'reqparentrankid' => 180, 'modifiedby' => null, 'modifiedtimestamp' => null, 'initialtimestamp' => '2023-03-26 18:14:32'],
        ]);

        DB::table('taxa')->insertOrIgnore([
            ['tid' => 1, 'kingdomName' => '',        'rankID' => 1,  'sciName' => 'Organism', 'unitName1' => 'Organism', 'unitName2' => null, 'author' => ''],
            ['tid' => 2, 'kingdomName' => 'Monera',   'rankID' => 10, 'sciName' => 'Monera',   'unitName1' => 'Monera',   'unitName2' => null, 'author' => ''],
            ['tid' => 3, 'kingdomName' => 'Protista', 'rankID' => 10, 'sciName' => 'Protista', 'unitName1' => 'Protista', 'unitName2' => null, 'author' => ''],
            ['tid' => 4, 'kingdomName' => 'Plantae',  'rankID' => 10, 'sciName' => 'Plantae',  'unitName1' => 'Plantae',  'unitName2' => null, 'author' => ''],
            ['tid' => 5, 'kingdomName' => 'Fungi',    'rankID' => 10, 'sciName' => 'Fungi',    'unitName1' => 'Fungi',    'unitName2' => null, 'author' => ''],
            ['tid' => 6, 'kingdomName' => 'Animalia', 'rankID' => 10, 'sciName' => 'Animalia', 'unitName1' => 'Animalia', 'unitName2' => null, 'author' => ''],
        ]);

        DB::table('taxstatus')->insertOrIgnore([
            ['tid' => 1, 'tidaccepted' => 1, 'taxauthid' => 1, 'parenttid' => 1],
            ['tid' => 2, 'tidaccepted' => 2, 'taxauthid' => 1, 'parenttid' => 1],
            ['tid' => 3, 'tidaccepted' => 3, 'taxauthid' => 1, 'parenttid' => 1],
            ['tid' => 4, 'tidaccepted' => 4, 'taxauthid' => 1, 'parenttid' => 1],
            ['tid' => 5, 'tidaccepted' => 5, 'taxauthid' => 1, 'parenttid' => 1],
            ['tid' => 6, 'tidaccepted' => 6, 'taxauthid' => 1, 'parenttid' => 1],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void {
        DB::table('taxstatus')->whereIn('tid', [1, 2, 3, 4, 5, 6])->delete();
        DB::table('taxa')->whereIn('tid', [1, 2, 3, 4, 5, 6])->delete();
        DB::table('taxonunits')->whereBetween('taxonunitid', [24, 152])->delete();
        DB::table('taxauthority')->where('taxauthid', 1)->delete();
    }
};
