<?php

namespace Tests\Unit;

use App\Core\Download\DarwinCore;
use PHPUnit\Framework\TestCase;

class DarwinCoreDownloadTest extends TestCase {
    public function check_mapping($input_row, $output_row): void {
        $mapped_row = DarwinCore::map_row($input_row);

        foreach ($output_row as $key => $value) {
            $this->assertArrayHasKey($key, $mapped_row);
            $this->assertEquals($mapped_row[$key], $value);
        }
    }

    /**
     * A basic test example.
     */
    public function test_occid(): void {
        self::check_mapping(['occid' => 1], ['id' => 1]);
    }

    /**
     * Test Darwin Core Mapping for references
     * see https://dwc.tdwg.org/terms/#dcterms:references for more information
     * Doesn't mock url because of odd mocking issues
     */
    public function test_references(): void {
        self::check_mapping(['occid' => 1], ['id' => 1, 'references' => '/occurrence/1']);
    }

    public function test_row_mapping(): void {
        //Fake Test Record
        $occurrence_row = [
            'collID' => 1,
            'institutionCode' => null,
            'collectionCode' => null,
            'collectionName' => 'SSH - Symbiota Support Hub',
            'collectionID' => null,
            'datasetID' => null,
            'datasetName' => null,
            'iid' => null,
            'fullDescription' => 'The small herbarium description',
            'homepage' => 'https://biokic.github.io/symbiota-docs',
            'resourceJson' => '[{"title":{"en":"Homepage"}, "url": "https://biokic.github.io/symbiota-docs"}]',
            'individualUrl' => null,
            'Contact' => 'Symbiota Hub',
            'email' => 'ssh@hub.com',
            'contactJson' => '[{"firstName":"","lastName": "SSH Hub", "email" => ":"ssh@hub.com"}]',
            'latitudeDecimal' => null,
            'longitudeDecimal' => null,
            'icon' => '/favicon.ico',
            'collType' => 'Preserved Specimens',
            'managementType' => 'Live Data',
            'publicEdits' => 0,
            'collectionGuid' => '1657fcd2-11c6-4f82-b57f-69a775316c98',
            'securityKey' => '647ad913-b40e-49fa-a513-97ae6fb3e9e3',
            'guidTarget' => 'symbiotaUUID',
            'rightsHolder' => null,
            'rights' => 'http://creativecommons.org/licenses/by-nc/4.0/',
            'usageTerm' => null,
            'publishToGbif' => 0,
            'publishToIdigbio' => 0,
            'aggKeysStr' => null,
            'dwcTermJson' => null,
            'recordID' => '2511acbd-15be-4183-9795-7bbd0e4ef185',
            'dwcaUrl' => 'notProperUrl',
            'bibliographicCitation' => null,
            'accessRights' => null,
            'dynamicProperties' => null,
            'sortSeq' => null,
            'initialTimestamp' => '2017-09-05 15:54:05',
            'gen_occid' => 2269041,
            'associatedSequences' => 'resourcename-1, title-1, gen-id-1, locus-1, https://biokic.github.io/symbiota-docs/coll_manager/upload/fields/ | resourcename-2, title-2, gen-id-2, locus-2, https://biokic.github.io/symbiota-docs/coll_manager/upload/fields/#some',
            'occid' => 2269041,
            'collid' => 2,
            'dbpk' => null,
            'basisOfRecord' => 'PreservedSpecimen',
            'occurrenceID' => null,
            'catalogNumber' => 'SYMB0491',
            'otherCatalogNumbers' => null,
            'ownerInstitutionCode' => null,
            'institutionID' => null,
            'organismID' => null,
            'family' => 'Asparagaceae',
            'scientificName' => 'Camassia quamash',
            'sciname' => 'Camassia quamash',
            'tidInterpreted' => 202659,
            'genus' => 'Camassia',
            'specificEpithet' => 'quamash',
            'taxonRank' => null,
            'infraspecificEpithet' => null,
            'scientificNameAuthorship' => '(Pursh) Greene',
            'taxonRemarks' => null,
            'identifiedBy' => null,
            'dateIdentified' => null,
            'identificationReferences' => null,
            'identificationRemarks' => null,
            'identificationQualifier' => null,
            'typeStatus' => null,
            'recordedBy' => 'SSH Hub',
            'recordNumber' => '491',
            'associatedCollectors' => null,
            'eventDate' => '2004-04-21',
            'eventDate2' => null,
            'year' => 2004,
            'month' => 4,
            'day' => 21,
            'startDayOfYear' => 112,
            'endDayOfYear' => 112,
            'verbatimEventDate' => '21 April, 2004',
            'eventTime' => null,
            'habitat' => 'wet meadow',
            'substrate' => null,
            'fieldNotes' => null,
            'fieldNumber' => null,
            'eventID' => null,
            'occurrenceRemarks' => null,
            'informationWithheld' => null,
            'dataGeneralizations' => null,
            'associatedOccurrences' => null,
            'associatedTaxa' => null,
            'verbatimAttributes' => null,
            'behavior' => null,
            'vitality' => null,
            'reproductiveCondition' => null,
            'cultivationStatus' => null,
            'establishmentMeans' => null,
            'lifeStage' => null,
            'sex' => null,
            'individualCount' => null,
            'samplingProtocol' => null,
            'samplingEffort' => null,
            'preparations' => null,
            'locationID' => null,
            'continent' => null,
            'waterBody' => null,
            'parentLocationID' => null,
            'islandGroup' => null,
            'island' => null,
            'countryCode' => null,
            'country' => null,
            'stateProvince' => null,
            'county' => 'Mendocino',
            'municipality' => null,
            'locality' => 'In wet meadow',
            'localitySecurity' => 0,
            'localitySecurityReason' => null,
            'decimalLatitude' => 36.4036,
            'decimalLongitude' => -121.88232,
            'geodeticDatum' => 'WGS84',
            'coordinateUncertaintyInMeters' => null,
            'footprintWKT' => null,
            'coordinatePrecision' => null,
            'locationRemarks' => null,
            'verbatimCoordinates' => 'T.13N,R.17W,Sec34',
            'verbatimCoordinateSystem' => null,
            'georeferencedBy' => null,
            'georeferencedDate' => null,
            'georeferenceProtocol' => null,
            'georeferenceSources' => null,
            'georeferenceVerificationStatus' => null,
            'georeferenceRemarks' => null,
            'minimumElevationInMeters' => null,
            'maximumElevationInMeters' => null,
            'verbatimElevation' => null,
            'minimumDepthInMeters' => null,
            'maximumDepthInMeters' => null,
            'verbatimDepth' => null,
            'previousIdentifications' => null,
            'availability' => null,
            'disposition' => null,
            'storageLocation' => null,
            'genericColumn1' => null,
            'genericColumn2' => null,
            'modified' => null,
            'language' => null,
            'observerUid' => null,
            'processingStatus' => 'closed',
            'recordEnteredBy' => null,
            'duplicateQuantity' => null,
            'labelProject' => null,
            'dynamicFields' => null,
            'dateEntered' => '2019-04-11 14:02:20',
            'dateLastModified' => '2024-10-01 01:52:11',

            //Appended Taxon Info
            'higherClassification' => 'Organism|Plantae|Viridiplantae|Streptophyta|Embryophyta|Tracheophyta|Spermatophytina|Magnoliopsida|Lilianae|Asparagales|Agavaceae|Camassia',
            'kingdom' => 'Plantae',
            'phylum' => 'Tracheophyta',
            'class' => 'Magnoliopsida',
            'order' => 'Asparagales',
            'family' => 'Asparagaceae',
        ];

        $expect_output_row = [
            'id' => 2269041,
            'institutionCode' => null,
            'collectionCode' => null,
            'ownerInstitutionCode' => null,
            'collectionID' => '1657fcd2-11c6-4f82-b57f-69a775316c98',
            'basisOfRecord' => 'PreservedSpecimen',
            'occurrenceID' => '2511acbd-15be-4183-9795-7bbd0e4ef185',
            'catalogNumber' => 'SYMB0491',
            'otherCatalogNumbers' => null,
            'higherClassification' => 'Organism|Plantae|Viridiplantae|Streptophyta|Embryophyta|Tracheophyta|Spermatophytina|Magnoliopsida|Lilianae|Asparagales|Agavaceae|Camassia',
            'kingdom' => 'Plantae',
            'phylum' => 'Tracheophyta',
            'class' => 'Magnoliopsida',
            'order' => 'Asparagales',
            'family' => 'Asparagaceae',
            'scientificName' => 'Camassia quamash',
            'taxonID' => 202659,
            'scientificNameAuthorship' => '(Pursh) Greene',
            'genus' => 'Camassia',
            'subgenus' => '',
            'specificEpithet' => 'quamash',
            'verbatimTaxonRank' => null,
            'infraspecificEpithet' => null,
            'cultivarEpithet' => null,
            'taxonRank' => 'Species',
            'identifiedBy' => null,
            'dateIdentified' => null,
            'identificationReferences' => null,
            'identificationRemarks' => null,
            'taxonRemarks' => null,
            'identificationQualifier' => null,
            'typeStatus' => null,
            'recordedBy' => 'SSH Hub',
            'recordNumber' => '491',
            'eventDate' => '2004-04-21',
            'year' => 2004,
            'month' => 4,
            'day' => 21,
            'startDayOfYear' => 112,
            'endDayOfYear' => 112,
            'verbatimEventDate' => '21 April, 2004',
            'occurrenceRemarks' => null,
            'habitat' => 'wet meadow',
            'behavior' => null,
            'vitality' => null,
            'fieldNumber' => null,
            'eventID' => null,
            'informationWithheld' => null,
            'dataGeneralizations' => null,
            'dynamicProperties' => null,
            'associatedOccurrences' => null,
            'associatedSequences' => 'resourcename-1, title-1, gen-id-1, locus-1, https://biokic.github.io/symbiota-docs/coll_manager/upload/fields/ | resourcename-2, title-2, gen-id-2, locus-2, https://biokic.github.io/symbiota-docs/coll_manager/upload/fields/#some',
            'associatedTaxa' => null,
            'reproductiveCondition' => null,
            'establishmentMeans' => null,
            'lifeStage' => null,
            'sex' => null,
            'individualCount' => null,
            'samplingProtocol' => null,
            'preparations' => null,
            'locationID' => null,
            'continent' => null,
            'waterBody' => null,
            'islandGroup' => null,
            'island' => null,
            'country' => null,
            'countryCode' => null,
            'stateProvince' => null,
            'county' => 'Mendocino',
            'municipality' => null,
            'locality' => 'In wet meadow',
            'locationRemarks' => null,
            'decimalLatitude' => 36.4036,
            'decimalLongitude' => -121.88232,
            'geodeticDatum' => 'WGS84',
            'coordinateUncertaintyInMeters' => null,
            'verbatimCoordinates' => 'T.13N,R.17W,Sec34',
            'georeferencedBy' => null,
            'georeferenceProtocol' => null,
            'georeferenceSources' => null,
            'georeferenceVerificationStatus' => null,
            'georeferenceRemarks' => null,
            'minimumElevationInMeters' => null,
            'maximumElevationInMeters' => null,
            'minimumDepthInMeters' => null,
            'maximumDepthInMeters' => null,
            'verbatimDepth' => null,
            'verbatimElevation' => null,
            'disposition' => null,
            'language' => null,
            'recordEnteredBy' => null,
            'modified' => '2024-10-01 01:52:11',
            'rights' => 'http://creativecommons.org/licenses/by-nc/4.0/',
            'rightsHolder' => null,
            'accessRights' => null,
            'recordID' => '2511acbd-15be-4183-9795-7bbd0e4ef185',
            'references' => '/occurrence/2269041',
        ];

        self::check_mapping($occurrence_row, $expect_output_row);
    }
}
